typography_spectrum: 0.37446927931159735
content_rating:
  adult: true
color:
  brandStrength: 0.2705184523947537
  lightness: 0.46458974201232195
  saturation: 0.5302695198915899
  rhythmicContrast: 0.6827791770920157
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fe2f65b-d963-4bc1-aba8-228fa829df31.jpg
layout_spectrum: 0.44222970004193485
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc3adab7-fc79-49f3-b7c9-e9491576ca88.jpg
name: Independent Ink Hawaii
navigation:
  - id: >-
      https://www.facebook.com/pages/Independent-Ink-Hawaii/1600765940251981?fref=ts
    url: >-
      https://www.facebook.com/pages/Independent-Ink-Hawaii/1600765940251981?fref=ts
    name: Like Us On Facebook
    type: external
title: Let Your Art Set You Apart. Be Independent.
